src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Enter the quantity of the product</description>
        <label>Quantity</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Quantity__c  *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>QuoteLines</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <label>Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuoteLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderFormController.cls
public class OrderFormController
{

    public quote quoteObj{get;set;}
    public Order__c orderObj {get;set;}
    public string accountid{get;set;}
    public string quoteid{get;set;}
    public map<id,decimal> priceperProduct{get;set;}
    public id quoteObjid{get;set;}
    public decimal totalVal{get;set;}
    public decimal  grandTotal{get;set;}
    public List<Quote_Line_Item__c> qlList = new list<Quote_Line_Item__c>();
    public list<product__c> selectedprd = new list<product__c>();
    
    public OrderFormController(ApexPages.StandardController controller) {
        
        
        quoteObjid = ApexPages.currentPage().getParameters().get('id'); 
        quoteObj = [select id,Accountid,name,Status,Discount,Opportunityid,TotalPrice from Quote where id =: ApexPages.currentPage().getParameters().get('id')];
        orderObj = new order__C();
        orderObj.Account__c = quoteObj.accountid;
        orderObj.Quote__c = quoteObjid;
        grandTotal = 0.0;
    }
    public list<productWrapper> prdWrapList = new list<productWrapper>();
    
    
    public list<productWrapper> getProductList()
    {
        for(product__c prdObj : [SELECT Price_per_Product__c,Active__c,Name,Price__c,Product_Code__c,Quantity__c,Product_Description__c,createdby.name FROM product__c where Active__c =true and createdby.name = 'Bhargavi V' limit 10])
        {
            prdObj.Quantity__c = 1;
            prdWrapList.add(new productWrapper(prdObj));
        }
        
        return prdWrapList;
    }
    public PageReference getSelected()
    {
        //selectedprd = new list<product__c>();
        selectedprd.clear();
        for(productWrapper prdWrapper: prdWrapList){
            
            if(prdWrapper.isselected == true)
            {
                selectedprd.add(prdWrapper.ProductWrapObj);
            }
        }
        return null;
    }  
    
    
    public List<product__c> GetSelectedPrdcts()
    {
        
        priceperProduct = new map<id,decimal>();
        if(selectedprd.size()>0){
            for(product__c prd: selectedprd)
            {
                decimal subtotal = prd.Quantity__c*prd.Price__c;
                priceperProduct.put(prd.id,subtotal);
                grandTotal = grandTotal + subtotal ;
            }
            return selectedprd;
        }
        else{
            return null;
        }
    }
    public pagereference grandtotal()
    {
     return null;
    }
    public decimal getgrandtotalDec()
    {
        system.debug('@@@grandtotal'+grandtotal);
        return grandTotal;
    }
    
    
    public void insertquoteLineItems()
    {
        //system.debug('Qunat'+quantitystr);
        for(product__c prdLoopVar :selectedprd)
        {
            Quote_Line_Item__c qlObj = new Quote_Line_Item__c();
            qlObj.Quotes__c= quoteObjid;
            qlObj.name = prdLoopVar.name;
            qlObj.Product__c = prdLoopVar.id;
            qlObj.Quantity__c = prdLoopVar.Quantity__c;
            qlObj.Total_Price__c = prdLoopVar.Quantity__c*prdLoopVar.Price__c;
            qlList.add(qlObj);
        }
        insert qlList;
        
    }
    public pagereference save()
    {
        insertquoteLineItems();
        quoteObj.Total_Price_on_Quote__c = grandtotal;
        update quoteObj;
        //quoteObj.Discount = orderObj.Discount__c;
        //orderObj.Quantity__c= quantitystr;
        insert orderObj;
        pagereference pg = new pagereference('/' + quoteObjid);
        pg.setRedirect(true);
        return pg;
    }
    
    public class productWrapper{
        
        public boolean isselected{get;set;}
        public product__c ProductWrapObj{get;set;}
        
        public productWrapper(product__c prd)
        {
            ProductWrapObj =prd;
            isselected = false;
            
        }
        
    }

}