src/objects/Scope_Poc_Information__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <label>Approver</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AutoRABIT_POC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AutoRABIT POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Scopes</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Out_ofScope__c</fullName>
        <label>Out of Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_to_Contact__c</fullName>
        <label>Person to Contact</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Poc_End_Date__c</fullName>
        <label>Poc End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Poc_Scope__c</fullName>
        <label>Poc Scope</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Poc_Start_Date__c</fullName>
        <label>Poc- Start Date</label>
        <type>Date</type>
    </fields>
    <label>Scope - Poc Information</label>
    <nameField>
        <label>Scope - Poc Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScopeInformationController.cls
public class ScopeInformationController {

    public ScopeInformationController(ApexPages.StandardController controller) {

    }

    
    public String opptyId{get;set;}
    public Opportunity OppObj{get;set;}
    public Scope_Poc_Information__c scopeObj{get;set;}
    public List<Scope_Poc_Information__c> scopeObjList{get;set;}
    
    public ScopeInformationController()
    {
        opptyId = System.currentPageReference().getParameters().get('opptyId');
        
        
    }
    public List<Scope_Poc_Information__c> getScopinfo()
    {
    scopeObjList = [Select id,name,Approver__c,AutoRABIT_POC__c,Opportunity__c,Opportunity__r.name,Out_ofScope__c,Person_to_Contact__c,Poc_End_Date__c,Poc_Scope__c,Poc_Start_Date__c from Scope_Poc_Information__c where Opportunity__r.id = :opptyId];
    system.debug('@@'+scopeObjList);
     return scopeObjList;
    }
       
}